source "https://rubygems.org"
ruby RUBY_VERSION

gem "minima"

gem "just-the-docs"

gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
# group :jekyll_plugins do
#   gem "jekyll-github-metadata", "~> 1.0"
# end
