name: Test the documentation is valid

on:
  pull_request:
    branches: 
      - develop
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout package
      uses: actions/checkout@v2

    - name: Install Ruby
      id: build-docs
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Build Docs
      working-directory: ./docs
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build
